trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
 
steps:
- script: |
    terraform --version 
    sudo apt update
    
    # Clone your GitHub repository
    git clone https://github.com/rainrajon/31st_oct.git
 
    # Change directory to your repository
    # cd your-repo
 
    # Run the Python script
    terraform init
    terraform plan -out main.tfplan
    terraform apply main.tfplan
  displayName: 'Terraform code'