trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
 
steps:
- script: |
    terraform --version 
    sudo apt update
    
    # Clone your GitHub repository
    git clone https://github.com/rainrajon/31st_oct.git
 
    # Change directory to your repository
    # cd your-repo
 
    # Run the Python script
    az account set --subscription 9ba952c5-e021-441b-86a3-4589b93b0a9e
    az login --service-principal -u 6296a5ec-60b8-46d3-9104-4eac1dbf4e9e -p UPW8Q~aS36KRKSYmFFQAzEuYBqA8WhG0VWys_bDL --tenant a84894e7-87c5-40e3-9783-320d0334b3cc

    terraform init
    terraform plan -out main.tfplan
    terraform apply main.tfplan
  displayName: 'Terraform code'