trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
 
steps:
- script: |
    terraform --version 
    sudo apt update
    
    # Clone your GitHub repository
    git clone https://github.com/rainrajon/31st_oct.git
 
    # Change directory to your repository
    # cd your-repo
 
    # Run the Python script
    az login
    terraform init
    terraform plan -destroy -out main.destroy.tfplan
    terraform apply main.destroy.tfplan
  displayName: 'Terraform code'